# Generated by Django 5.2.2 on 2025-06-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="preview",
            field=models.ImageField(upload_to="images/", verbose_name="Фото"),
        ),
    ]
