# Generated by Django 5.2.2 on 2025-06-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="preview",
            field=models.ImageField(upload_to="blogs/images/", verbose_name="Фото"),
        ),
    ]
