# Generated by Django 5.2.2 on 2025-06-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blog_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="preview",
            field=models.ImageField(
                null=True, upload_to="blogs/images/", verbose_name="Фото"
            ),
        ),
    ]
