# Generated by Django 5.2.2 on 2025-06-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blog_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="preview",
            field=models.ImageField(
                default="Изображение отсутствует",
                upload_to="blogs/images/",
                verbose_name="Фото",
            ),
        ),
    ]
