# Generated by Django 5.2.2 on 2025-06-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_blog_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Статус публикации"),
        ),
    ]
