# Generated by Django 5.2.2 on 2025-07-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="check_status",
            field=models.BooleanField(
                default=False, verbose_name="Статус публикации продукта"
            ),
        ),
    ]
