# Generated by Django 5.2.2 on 2025-06-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_options_alter_product_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to="products/images/", verbose_name="Фотография продукта"
            ),
        ),
    ]
