# Generated by Django 5.2.2 on 2025-07-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_check_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("can_unpublish_product", "Can Unpublish Product"),
                    ("can_remove_product", "Can Remove Product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
