# Generated by Django 5.2.2 on 2025-06-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="products/images/",
                verbose_name="Фотография продукта",
            ),
        ),
    ]
